@startuml
actor Usuario
participant Sistema
database BancoDeDados

Usuario -> Sistema : Enviar login
Sistema -> BancoDeDados : Verificar credenciais
BancoDeDados --> Sistema : Rettornar resultado
Sistema --> Usuario : Mostrar mensagem de sucesso ou erro
@enduml
